#ifndef IFACEEXCHANGETYPESDEFS_H
#define IFACEEXCHANGETYPESDEFS_H


#define IFACE_CLOSE_AFTER   180
#define MAX_MESS_COUNT_PER_ONE_TASK     1000
#define MAX_IDENTICAL_MESS_PER_SESION   55//SETT_MAX_IDENTICAL_MESS_PER_SESION
#define MAX_DIFF_MSEC_FOR_TASK_SESION   1500000  //25 MINUTES

#define ATND_STATUS_OK      1
#define ATND_STATUS_OLD     2
#define ATND_STATUS_ERR     3
#define ATND_STATUS_IGNORE  4
#define ATND_STATUS_NMODEL  5


#endif // IFACEEXCHANGETYPESDEFS_H
